import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class IngredientDAO extends DAO<Ingredient> {
    public IngredientDAO(Connection conn) {
        super(conn);
    }
    
    public boolean create(Ingredient ingredient) {
        String query = "INSERT INTO ingredients (nom_ingredient, ref_type) VALUES (?, ?)";
        PreparedStatement stmt;
        try{
        stmt = this.conn.prepareStatement(query);
        stmt.setString(1, ingredient.getNomIngredient());
        stmt.setInt(2, ingredient.getRefType());
        stmt.executeUpdate();
        
        ResultSet rs = stmt.getGeneratedKeys();
        if (rs.next()) {
            ingredient.setRefIngredient(rs.getInt(1));
        }
        rs.close();
        stmt.close();
        return true;
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return false;
    }
    
    
    
    public boolean update(Ingredient ingredient) {
        try{
            String query = "UPDATE ingredients SET nom_ingredient = ?, ref_type = ? WHERE ref_ingredient = ?;";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, ingredient.getNomIngredient());
            stmt.setInt(2, ingredient.getRefType());
            stmt.setInt(3, ingredient.getRefIngredient());
            stmt.executeUpdate();
            stmt.close();
            return true;
        }
        catch(SQLException e){
            Logger.getLogger(IngredientDAO.class.getName()).log(Level.SEVERE, null, e); //auto-generated by Netbeans
        }
        return false;
    }
    
    public boolean delete(String refIngredient)  {
        try{
        PreparedStatement stmt = conn.prepareStatement("DELETE FROM ingredients WHERE ref_ingredient = ?;");
        stmt.setString(1, refIngredient);
        stmt.executeUpdate();
        stmt.close();
        return true;
        }catch(SQLException e){
            e.printStackTrace();
        return false;
        }
    }
    
    

    public ArrayList<Ingredient> findAll(){
        ArrayList<Ingredient> arrIngredient = new ArrayList<>();
        Ingredient ing= new Ingredient();
        
        
        try {
            Statement stat= conn.createStatement();
            ResultSet res= stat.executeQuery("SELECT * FROM INGREDIENT;");
            while (res.next()) {                
                ing.setNomIngredient(res.getString("NomIngredient"));
                ing.setRefType(Integer.parseInt(res.getString("QuantiteProduit")));
                ing.setRefIngredient(Integer.parseInt(res.getString("RefIngredient")));
                arrIngredient.add(ing);
            }
            stat.close();
            return arrIngredient;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
        
    }

    public ArrayList<Ingredient> findAll(String champ, String nomChamp){
        ArrayList<Ingredient> arrIngredient = new ArrayList<>();
        Ingredient ing= new Ingredient();
        
        
        try {
            Statement stat= conn.createStatement();
            ResultSet res= stat.executeQuery("SELECT * FROM INGREDIENT"+nomChamp+champ+";");
            while (res.next()) {                
                ing.setNomIngredient(res.getString("NomIngredient"));
                ing.setRefType(Integer.parseInt(res.getString("QuantiteProduit")));
                ing.setRefIngredient(Integer.parseInt(res.getString("RefIngredient")));
                arrIngredient.add(ing);
            }
            stat.close();
            return arrIngredient;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
        
    }

    public Ingredient find(int id){
        Ingredient ing= new Ingredient();
        try {
            Statement stat= conn.createStatement();
            ResultSet res= stat.executeQuery("SELECT * FROM INGREDIENT WHERE RefIngredient= ?;");            
                ing.setNomIngredient(res.getString("NomIngredient"));
                ing.setRefType(res.getInt("QuantiteProduit"));
                ing.setRefIngredient(id);
        }catch (SQLException e) {
            e.printStackTrace();
        }
        return ing;
    }
}
