import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class IngredientDAO extends DAO<Ingredient> {
    public IngredientDAO(Connection conn) {
        super(conn);
    }
    
    public boolean create(Ingredient ingredient) {
        String query = "INSERT INTO ingredients (nom_ingredient, ref_type) VALUES (?, ?)";
        PreparedStatement stmt;
        try{
        stmt = this.conn.prepareStatement(query);
        stmt.setString(1, ingredient.getNomIngredient());
        stmt.setInt(2, ingredient.getRefType());
        stmt.executeUpdate();
        
        ResultSet rs = stmt.getGeneratedKeys();
        if (rs.next()) {
            ingredient.setRefIngredient(rs.getInt(1));
        }
        rs.close();
        stmt.close();
        }
        catch(SQLException e){
            Logger.getLogger(IngredientDAO.class.getName()).log(Level.SEVERE, null, e); //auto-generated by Netbeans
        }
        return false;
    }
    
    
    
    public boolean update(Ingredient ingredient) {
        try{
            String query = "UPDATE ingredients SET nom_ingredient = ?, ref_type = ? WHERE ref_ingredient = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, ingredient.getNomIngredient());
            stmt.setInt(2, ingredient.getRefType());
            stmt.setInt(3, ingredient.getRefIngredient());
            int res =stmt.executeUpdate();
            stmt.close();
            return res==1;
        }
        catch(SQLException e){
            Logger.getLogger(IngredientDAO.class.getName()).log(Level.SEVERE, null, e); //auto-generated by Netbeans
        }
        return false;
    }
    
    public boolean delete(int refIngredient) throws SQLException {
        String query = "DELETE FROM ingredients WHERE ref_ingredient = ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setInt(1, refIngredient);
        int res = stmt.executeUpdate();
        stmt.close();
        return res==1;
    }
    
    

    public ArrayList<Ingredient> findAll(){
        ArrayList<Ingredient> arrIngredient = new ArrayList<>();
        Ingredient ing= new Ingredient();
        
        
        try {
            Statement stat= conn.createStatement();
            ResultSet res= stat.executeQuery("SELECT * FROM INGREDIENT;");
            while (res.next()) {                
                ing.setNomIngredient(res.getString("NomIngredient"));
                ing.setRefType(Integer.parseInt(res.getString("QuantiteProduit")));
                ing.setRefIngredient(Integer.parseInt(res.getString("RefIngredient")));
                arrIngredient.add(ing);
            }
            stat.close();
        } catch (NumberFormatException | SQLException e) {
            Logger.getLogger(ProduitDAO.class.getName()).log(Level.SEVERE, null, e);
        }
        return arrIngredient;
    }
    public Ingredient find(int id){
        Ingredient ing= new Ingredient();
        try {
            Statement stat= conn.createStatement();
            ResultSet res= stat.executeQuery("SELECT * FROM INGREDIENT WHERE RefIngredient= ?");            
                ing.setNomIngredient(res.getString("NomIngredient"));
                ing.setRefType(res.getInt("QuantiteProduit"));
                ing.setRefIngredient(id);
        }catch (Exception e) {
            Logger.getLogger(ProduitDAO.class.getName()).log(Level.SEVERE, null, e); //auto-generated by NetBeans
        }
        return ing;
    }

    @Override
    public boolean delete(Ingredient o) {
        try {
            PreparedStatement stat = conn.prepareStatement("DELETE FROM INGREDIENT WHERE RefIngredient=?");
            stat.setInt(1, o.getRefIngredient());
            int res = stat.executeUpdate();
            stat.close();
            return res==1;
        } catch (SQLException ex) {
            Logger.getLogger(ProduitDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
}
