
import java.lang.System.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import oracle.jdbc.clio.annotations.Debug.Level;


public class RecetteDAO extends DAO<Recette>{
    public RecetteDAO(Connection conn){
        super(conn);
    }
    @Override
    public ArrayList<Recette> findAll() {
        try{
            PreparedStatement stat= conn.prepareStatement("SELECT * FROM RECETTE");
            ResultSet res = stat.executeQuery();
        }catch(SQLException e){
            Logger.getLogger(IngredientDAO.class.getName()).log(Level.SEVERE, null, e); //auto-generated by Netbeans
        }
    }

    @Override
    public Recette find(int id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean create(Recette o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean update(Recette o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean delete(Recette o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
